services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    environment:
      - "TEMPLATES_DIR=/app/templates"
    ports:
      - "8000:8000"
    volumes:
      - "./backend/src:/app/src"
      - "./backend/experiments:/app/experiments"
      - "./backend/models/onnx_models:/root/.cache/chroma/onnx_models"
      - "./backend/templates:/app/templates"
    restart: no
    depends_on:
      - chroma
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sso_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chroma:
    image: chromadb/chroma
    volumes:
      - chroma-data:/data
    expose:
      - "8000"
    ports:
      - "8004:8000"

volumes:
  chroma-data:
  postgres_data: