services:
  backend:
    build:
      context: ./backend
      target: app_dev
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - "./backend/src:/app/src"
    restart: no

  chroma:
    image: chromadb/chroma
    volumes:
      - chroma-data:/data
    ports:
      - "8004:8000"

volumes:
  chroma-data: